GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "focus time",
  "important": true
}

###
GET http://localhost:3001/api/notes/1