GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtob2lkejA5MEBnbWFpbC5jb20iLCJpZCI6MiwiaWF0IjoxNzcxNDY4NzM3fQ.lMWvBjkasV908xe53JiLS3X7q61Jcu98W_4heXBH5uI

{
  "author": "Steve",
  "url": "http://twitter.com/",
  "title": "hotdog",
  "likes": 56
}

###
DELETE http://localhost:3001/api/blogs/5

###
PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{
  "likes": 8
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "khoidz090@gmail.com",
  "name": "khoi"
}

###
PUT http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "K blog chanel",
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "khoidz090@gmail.com",
  "password": "secret"
}