GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Steve",
  "url": "http://tiktok.com/",
  "title": "hotdog",
  "likes": 36
}

###
DELETE http://localhost:3001/api/blogs/5