GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "OK",
  "author": "K",
  "url": "https://",
  "likes": 3
}
###
GET http://localhost:3001/api/blogs/68f1b023792bf234faadb782