GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlM3NzduIiwiaWQiOiI2OTAxZmJiYzNkMjg1NjI1ZGMyNGE4YzYiLCJpYXQiOjE3NjE5OTU3Njd9.5_xRv0U4b6It_Pzupd7I0UAlFj5zsqFXIWl0Vc08Lew

{
  "title": "The Outliners",
  "author": "Khoi",
  "url": "https://kdev.com",
  "likes": 6,
  "userId": "690151efbf4ec0a02761eb48"
}

###
DELETE http://localhost:3001/api/blogs/6909bbcebd871706b173f934
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlM3NzduIiwiaWQiOiI2OTAxZmJiYzNkMjg1NjI1ZGMyNGE4YzYiLCJpYXQiOjE3NjIwMzk5Mzl9.pOrknrb8kVMyIceWUc0dRH4UlTzlKsjJqN65cHfD0UU

###

PUT http://localhost:3001/api/blogs/6909b0691a0d14a0d7c71cea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlM3NzduIiwiaWQiOiI2OTAxZmJiYzNkMjg1NjI1ZGMyNGE4YzYiLCJpYXQiOjE3NjIyNDQ5Mzh9.vN8hBnxnpU0d4cJ_2ExL3RIrGxIBFeYmShB-3VTXFTw

{
  "title": "The updated",
  "author": "Khoi",
  "url": "https://kdev.com",
  "likes": 1
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "khoidz",
  "name": "Khoi",
  "password": "123"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "S777n",
  "password": "s3l"
}